# Generated by Django 4.2.4 on 2023-08-22 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_3_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kicks',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 21, 6, 8, 394673)),
        ),
    ]
